version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: furniture_store_db
    environment:
      - POSTGRES_USER=furniture_user
      - POSTGRES_PASSWORD=furniture_pass
      - POSTGRES_DB=furniture_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile        # теперь только runtime
    container_name: furniture_store_backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/furniture_db
      - SPRING_DATASOURCE_USERNAME=furniture_user
      - SPRING_DATASOURCE_PASSWORD=furniture_pass
      - JWT_SECRET=mySuperSecretKeyThatIsAtLeast32BytesLong!
      - JWT_ACCESS_EXPIRATION_MS=15000
      - JWT_REFRESH_EXPIRATION_MS=2592000000
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
