spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/furniture_db
    username: furniture_user
    password: furniture_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: "mySuperSecretKeyThatIsAtLeast32BytesLong!"
  access-expiration-ms: 15000  # 10 часов
#  access-expiration-ms: 300000  # 5 минут
  refresh-expiration-ms: 2592000000  # 30 дней