spring:
  datasource:
    # используем ENV-переменную SPRING_DATASOURCE_URL,
    # если она не задана — откатимся к локальной разработке
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/furniture_db}
    username: ${SPRING_DATASOURCE_USERNAME:furniture_user}
    password: ${SPRING_DATASOURCE_PASSWORD:furniture_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  # ENV-переменные JWT_SECRET, ACCESS и REFRESH_EXPIRATION
  secret: ${JWT_SECRET:mySuperSecretKeyThatIsAtLeast32BytesLong!}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:15000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:2592000000}
